### ISSUE TITLE
Tech-Side Enhancement in the ModPack

### ISSUE THREAD

**Issue by FirstMegaGame4** [sleepy-evelyn/Stitched#1]
This ModPack looks really great to me, but I think there is missing some Technology Mods in it, we only have Create.

Mods like Tech Reborn, Modern Industrialization, Applied Energistics, Modern Dynamics, Wireless Network, Industrial Revolution could be really great into this.

**Comment by sleepy-evelyn** [comment]
Thanks for the suggestion. I deliberately chose to exclude these for a couple of reasons.

- For AE2 I despise how complicated it is to setup a storage network with AE2. Hence Toms simple storage is included instead which does practically the same thing.
- Really bad textures and models (Modern Industrialization & Industrial Revolution).
- Making massive sections of the create mod useless since it’s easier to build stuff for e.g. using tech reborn for the most part and you get a better yield. This is fixed with packs that heavily modify recipes and introduce quests. This is not one of those packs
- Create and Botania is by far enough to do basically anything you want within the world when it comes to automation and they are far more creative and fun than the others.
- Most of these mods rely on a very specific way of doing things which i think stifles creativity. Also not a fan of having to create specific multiblock structures

**Comment by FirstMegaGame4** [comment]
Okay it's your modpack, but as for me I'm not using create, since I don't truly line the mod, so that can attract less people.
Nevermind, thanks for your anwser.

**Comment by sleepy-evelyn** [comment]
Decided after careful thought i'm going to add Modern Industrialization to the pack once I figure out how to Integrate it well with Create and Ad Astra @FirstMegaGame4

**Comment by FirstMegaGame4** [comment]
Thank you! Howerver, I think you stell need to add AE2. AE2 may be hard to understand and hard to setup, but if you're doing a AE2 system, it's not only for storage-purposes, but for the truly advanced autocrafting system it provides, which is also the most mod-compatible-friendly that I know (i.e. you can autocraft with runes in Botania with it). I think that should be really worth it for the pack to append AE2.

After your next anwser, you'll can close the issue, as I don't have any more enhancements to suggest at the moment.

**Comment by sleepy-evelyn** [comment]
Yeah toms simple storage offers auto-crafting and wireless access. The create void utilities have been included as well for remote storage access

**Comment by sleepy-evelyn** [comment]
Decided to abandon this idea. Couldn't find a decent resourcepack for the mod and integrating it with Create  + Ad Astra is gonna take up waaaay too much time I could spend on more interesting things such as new quests.
